export const catcher = async (err: Error): Promise<void> => {
  console.error(err);
}
